name: jam_checker

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  check_program_compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 3
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Check for Makefile
          run: |
            if [ ! -f "Makefile" ]; then
              echo "::error ::/!\\ WARNING NO MAKEFILE FOUND /!\\"
              exit 1
            else
              echo "::notice::Makefile found."
            fi
        - name: Launch make
          run: |
              if make; then
                echo "::notice file=Makefile::Succesfully compilation (make)."
              else
                echo "::error file=Makefile::/!\\ COMPILATION ERROR (make)/!\\"
              fi   
        - name: Launch make clean
          run: |
            if make clean; then
              echo "::notice file=Makefile::Succesfully compilation (make clean)."
            else
              echo "::error file=Makefile::/!\\ COMPILATION ERROR (make clean)/!\\"
            fi
        - name: Check executables
          run: |
              if ! test -x ./42sh; then
                echo "::error file=$executable::Executable $executable is missing or not executable."
                exit 1
              else
                echo "::notice file=$executable::Executable $executable found and is executable."
              fi